package com.example.backend.service.report;

import com.example.backend.entity.exam.Exam;
import com.example.backend.report.exam.dto.*;
import com.example.backend.report.exam.renderer.StudentAnswerPdfRenderer;
import com.example.backend.report.student.StudentAnswerSheetPageEvent;
import com.example.backend.repository.exam.ExamAttemptRepository;
import com.example.backend.repository.exam.ExamRepository;
import com.example.backend.repository.report.ReportRepository;
import com.lowagie.text.Document;
import com.lowagie.text.PageSize;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
public class StudentAnswerSheetReportService {

    private final ExamRepository examRepository;
    private final ExamAttemptRepository examAttemptRepository;
    private final ReportRepository reportRepository;
    private final StudentAnswerPdfRenderer studentAnswerPdfRenderer;

    public StudentAnswerSheetReportService(
            ExamRepository examRepository,
            ExamAttemptRepository examAttemptRepository,
            ReportRepository reportRepository,
            StudentAnswerPdfRenderer studentAnswerPdfRenderer
    ) {
        this.examRepository = examRepository;
        this.examAttemptRepository = examAttemptRepository;
        this.reportRepository = reportRepository;
        this.studentAnswerPdfRenderer = studentAnswerPdfRenderer;
    }

    @Transactional
    public byte[] generate(Long examId, String studentId) {
        try {
            Exam exam = examRepository.findById(examId)
                    .orElseThrow(() -> new RuntimeException("Exam not found."));

            if (!Boolean.TRUE.equals(exam.getResultsReleased())) {
                throw new RuntimeException("Results are not yet released.");
            }

            examAttemptRepository
                    .findByExamIdAndStudentId(examId, studentId)
                    .orElseThrow(() -> new RuntimeException("Attempt not found."));

            String classOfferingId =
                    reportRepository.findStudentClassOfferingIdForExam(examId, studentId);

            if (classOfferingId == null || classOfferingId.isBlank()) {
                throw new RuntimeException("Student class offering not found for this exam.");
            }

            ReportExamHeaderDTO header =
                    reportRepository.findExamHeaderForReport(examId, classOfferingId);

            ReportStudentSummaryDTO student =
                    reportRepository.findStudentSummariesForReport(examId, classOfferingId)
                            .stream()
                            .filter(s -> studentId.equalsIgnoreCase(s.studentId()))
                            .findFirst()
                            .orElseThrow(() -> new RuntimeException("Student summary not found."));

            List<ReportStudentAnswerDTO> studentAnswers =
                    reportRepository.findStudentAnswersForReport(examId, classOfferingId)
                            .stream()
                            .filter(a -> studentId.equalsIgnoreCase(a.studentId()))
                            .toList();

            List<ReportEssayRubricScoreDTO> rubricScores =
                    reportRepository.findEssayRubricScoresForReport(examId, classOfferingId);

            Map<String, List<ReportEssayRubricScoreDTO>> rubricScoresByAttemptAndQuestion =
                    rubricScores.stream()
                            .collect(Collectors.groupingBy(
                                    r -> r.attemptId() + "-" + r.questionId()
                            ));

            List<ReportChoiceDTO> choices =
                    reportRepository.findChoicesForReport(examId);

            Map<Long, List<ReportChoiceDTO>> choicesByQuestionId =
                    choices.stream()
                            .collect(Collectors.groupingBy(ReportChoiceDTO::questionId));

            String collegeOffering =
                    header.collegeOffering() == null || header.collegeOffering().isBlank()
                            ? " "
                            : header.collegeOffering();

            String generatedByText =
                    "Generated By: " + studentId + " | " +
                            LocalDateTime.now().format(
                                    DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")
                            );

            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

            Document document = new Document(
                    PageSize.LETTER,
                    36,
                    36,
                    125,
                    115
            );

            PdfWriter writer = PdfWriter.getInstance(document, outputStream);

            writer.setPageEvent(new StudentAnswerSheetPageEvent(
                    collegeOffering,
                    generatedByText
            ));

            document.open();

            studentAnswerPdfRenderer.renderStudentAnswer(
                    document,
                    header,
                    student,
                    studentAnswers,
                    choicesByQuestionId,
                    rubricScoresByAttemptAndQuestion
            );

            document.close();

            return outputStream.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException(
                    "Failed to generate student answer sheet report: " + e.getMessage(),
                    e
            );
        }
    }
}