package com.example.backend.service.report;

import com.example.backend.entity.exam.Exam;
import com.example.backend.report.exam.dto.*;
import com.example.backend.report.exam.renderer.StudentAnswerPdfRenderer;
import com.example.backend.entity.exam.ExamAnswerReviewLog;
import com.example.backend.repository.exam.ExamAnswerReviewLogRepository;
import com.example.backend.repository.exam.ExamAttemptRepository;
import com.example.backend.report.common.ReportConfig;
import com.example.backend.report.common.ReportPdfUtil;
import com.example.backend.repository.exam.ExamRepository;
import com.example.backend.repository.report.ReportRepository;
import com.lowagie.text.Document;
import lombok.AllArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;


import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.io.ByteArrayOutputStream;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Service
@AllArgsConstructor
public class StudentAnswerSheetReportService {

    private final ExamRepository examRepository;
    private final ExamAttemptRepository examAttemptRepository;
    private final ReportRepository reportRepository;
    private final StudentAnswerPdfRenderer studentAnswerPdfRenderer;
    private final ExamAnswerReviewLogRepository examAnswerReviewLogRepository;

    @Transactional
    public byte[] generate(Long examId, String studentId) {
        try {
            Exam exam = examRepository.findById(examId)
                    .orElseThrow(() -> new RuntimeException("Exam not found."));

            if (!Boolean.TRUE.equals(exam.getResultsReleased())) {
                throw new RuntimeException("Results are not yet released.");
            }

            examAttemptRepository
                    .findByExamIdAndStudentId(examId, studentId)
                    .orElseThrow(() -> new RuntimeException("Attempt not found."));

            String classOfferingId =
                    reportRepository.findStudentClassOfferingIdForExam(examId, studentId);

            if (classOfferingId == null || classOfferingId.isBlank()) {
                throw new RuntimeException("Student class offering not found for this exam.");
            }

            ReportExamHeaderDTO header =
                    reportRepository.findExamHeaderForReport(examId, classOfferingId);

            ReportStudentSummaryDTO student =
                    reportRepository.findStudentSummariesForReport(examId, classOfferingId)
                            .stream()
                            .filter(s -> studentId.equalsIgnoreCase(s.studentId()))
                            .findFirst()
                            .orElseThrow(() -> new RuntimeException("Student summary not found."));

            List<ReportStudentAnswerDTO> studentAnswers =
                    reportRepository.findStudentAnswersForReport(examId, classOfferingId)
                            .stream()
                            .filter(a -> studentId.equalsIgnoreCase(a.studentId()))
                            .toList();

            List<ReportEssayRubricScoreDTO> rubricScores =
                    reportRepository.findEssayRubricScoresForReport(examId, classOfferingId);

            Map<String, List<ReportEssayRubricScoreDTO>> rubricScoresByAttemptAndQuestion =
                    rubricScores.stream()
                            .collect(Collectors.groupingBy(
                                    r -> r.attemptId() + "-" + r.questionId()
                            ));

            List<ReportChoiceDTO> choices =
                    reportRepository.findChoicesForReport(examId);

            Map<Long, List<ReportChoiceDTO>> choicesByQuestionId =
                    choices.stream()
                            .collect(Collectors.groupingBy(ReportChoiceDTO::questionId));

            List<Long> answerIds =
                    studentAnswers.stream()
                            .map(ReportStudentAnswerDTO::answerId)
                            .filter(id -> id != null)
                            .distinct()
                            .toList();

            Map<Long, List<ExamAnswerReviewLog>> feedbackLogsByAnswerId =
                    answerIds.isEmpty()
                            ? Map.of()
                            : examAnswerReviewLogRepository
                            .findFeedbackLogsByAnswerIds(answerIds)
                            .stream()
                            .collect(Collectors.groupingBy(
                                    log -> log.getAnswer().getAnswerId()
                            ));

            String collegeOffering =
                    header.collegeOffering() == null || header.collegeOffering().isBlank()
                            ? " "
                            : header.collegeOffering();

            String generatedByText =
                    "Generated By: " + studentId + " | " +
                            ZonedDateTime.now(ZoneId.of("Asia/Manila"))
                                    .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();

            Document document =
                    ReportPdfUtil.createDocument(
                            outputStream,
                            ReportConfig.portrait(
                                    collegeOffering,
                                    generatedByText
                            )
                    );

            studentAnswerPdfRenderer.renderStudentAnswer(
                    document,
                    header,
                    student,
                    studentAnswers,
                    choicesByQuestionId,
                    rubricScoresByAttemptAndQuestion,
                    feedbackLogsByAnswerId
            );

            document.close();

            return outputStream.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException(
                    "Failed to generate student answer sheet report: " + e.getMessage(),
                    e
            );
        }
    }
}