package com.example.backend.service.report;

import com.lowagie.text.*;
import com.lowagie.text.pdf.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class StudentAnswerSheetPageEvent extends PdfPageEventHelper {

    private final String generatedBy;
    private final LocalDateTime generatedAt;

    public StudentAnswerSheetPageEvent(String generatedBy, LocalDateTime generatedAt) {
        this.generatedBy = generatedBy;
        this.generatedAt = generatedAt;
    }

    @Override
    public void onEndPage(PdfWriter writer, Document document) {
        PdfContentByte canvas = writer.getDirectContent();
        Rectangle page = document.getPageSize();

        drawLetterhead(canvas, page);
        drawFooter(canvas, page, writer.getPageNumber());
    }

    private void drawLetterhead(PdfContentByte canvas, Rectangle page) {
        try {
            BaseFont cambria = BaseFont.createFont(
                    "fonts/Cambria.ttf",
                    BaseFont.WINANSI,
                    BaseFont.EMBEDDED
            );

            BaseFont cambriaBold = BaseFont.createFont(
                    "fonts/Cambria-Bold.ttf",
                    BaseFont.WINANSI,
                    BaseFont.EMBEDDED
            );

            float centerX = page.getWidth() / 2;
            float y = page.getTop() - 35;

            canvas.beginText();

            canvas.setFontAndSize(cambria, 9);
            canvas.showTextAligned(Element.ALIGN_CENTER, "REPUBLIC OF THE PHILIPPINES", centerX, y, 0);

            canvas.setFontAndSize(cambriaBold, 11);
            canvas.showTextAligned(Element.ALIGN_CENTER, "POLYTECHNIC UNIVERSITY OF THE PHILIPPINES", centerX, y - 13, 0);

            canvas.setFontAndSize(cambria, 10);
            canvas.showTextAligned(Element.ALIGN_CENTER, "OFFICE OF THE VICE PRESIDENT FOR ACADEMIC AFFAIRS", centerX, y - 26, 0);

            canvas.setFontAndSize(cambriaBold, 13);
            canvas.showTextAligned(Element.ALIGN_CENTER, "COLLEGE OF COMPUTER AND INFORMATION SCIENCES", centerX, y - 42, 0);

            canvas.endText();

            canvas.moveTo(page.getLeft() + 36, y - 55);
            canvas.lineTo(page.getRight() - 36, y - 55);
            canvas.stroke();

        } catch (Exception e) {
            throw new RuntimeException("Failed to draw PUP letterhead.", e);
        }
    }

    private void drawFooter(PdfContentByte canvas, Rectangle page, int pageNumber) {
        try {
            BaseFont regular = BaseFont.createFont(
                    "fonts/NotoSans-Regular.ttf",
                    BaseFont.IDENTITY_H,
                    BaseFont.EMBEDDED
            );

            BaseFont bold = BaseFont.createFont(
                    "fonts/NotoSans-Bold.ttf",
                    BaseFont.IDENTITY_H,
                    BaseFont.EMBEDDED
            );

            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

            float left = page.getLeft() + 36;
            float right = page.getRight() - 36;
            float bottom = page.getBottom() + 35;

            canvas.beginText();

            canvas.setFontAndSize(regular, 7);
            canvas.showTextAligned(
                    Element.ALIGN_LEFT,
                    "Generated By: " + generatedBy + " | " + generatedAt.format(formatter),
                    left,
                    bottom + 18,
                    0
            );

            canvas.setFontAndSize(regular, 7);
            canvas.showTextAligned(
                    Element.ALIGN_LEFT,
                    "This document is system-generated by ExamGuard.",
                    left,
                    bottom + 7,
                    0
            );

            canvas.setFontAndSize(regular, 8);
            canvas.showTextAligned(Element.ALIGN_RIGHT, "Page ", right - 25, bottom + 7, 0);

            canvas.setFontAndSize(bold, 8);
            canvas.showTextAligned(Element.ALIGN_RIGHT, String.valueOf(pageNumber), right, bottom + 7, 0);

            canvas.endText();

        } catch (Exception e) {
            throw new RuntimeException("Failed to draw footer.", e);
        }
    }
}