spring.application.name=examguard-backend

# =========================
# DATABASE
# =========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:examguard}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${PGUSER:postgres}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${PGPASSWORD:postgres}}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000


# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.orm.jdbc.bind=warn

# =========================
# FLYWAY
# =========================
spring.flyway.enabled=false


# PERFORMANCE
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# =========================
# FILE UPLOAD
# =========================
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=250MB

examguard.ai-assets.dir=uploads/ai

# =========================
# SERVER
# =========================
server.port=${PORT:8080}

# =========================
# MAIL
# =========================
brevo.api.key=${BREVO_API_KEY}
app.mail.from=${APP_MAIL_FROM}

# =========================
# REGISTRAR API
# =========================
registrar.api.base-url=https://69eda66eaf4ff533142bd1b1.mockapi.io/registrar/
registrar.sync-on-startup=false

# =========================
# APP BASE URL
# =========================
app.base-url=${APP_BASE_URL:http://localhost:8080}

# =========================
# JWT
# =========================
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000