spring.application.name=examguard-backend

# =========================
# DATABASE
# =========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/examguard}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:your_local_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# PERFORMANCE
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# =========================
# FILE UPLOAD
# =========================
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=250MB

examguard.ai-assets.dir=uploads/ai

# =========================
# SERVER
# =========================
server.port=${PORT:8080}

# =========================
# MAIL
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=examguard.system@gmail.com
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# =========================
# PROFILE
# =========================
spring.profiles.active=${SPRING_PROFILE:prod}

# =========================
# REGISTRAR API
# =========================
registrar.api.base-url=${REGISTRAR_API_BASE_URL}

# =========================
# APP BASE URL
# =========================
app.base-url=${APP_BASE_URL:http://localhost:8080}

jwt.secret=${JWT_SECRET:CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY_AT_LEAST_32_CHARS}
jwt.expiration-ms=86400000