spring.application.name=examguard-backend

# =========================
# DATABASE - RAILWAY POSTGRES
# =========================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${PGUSER}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${PGPASSWORD}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1800000

# =========================
# REDIS CACHE - RAILWAY REDIS
# =========================
spring.cache.type=${SPRING_CACHE_TYPE:redis}
spring.data.redis.url=${SPRING_DATA_REDIS_URL}

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.orm.jdbc.bind=warn
spring.jpa.open-in-view=false

# =========================
# PERFORMANCE
# =========================
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true

# =========================
# FILE UPLOAD - RAILWAY VOLUME
# Mounted volume path: /app/uploads
# =========================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

app.upload.dir=/app/uploads
examguard.ai-assets.dir=/app/uploads/ai
profile.upload.dir=/app/uploads/profiles
evidence.upload.dir=/app/uploads/evidence
exam.upload.dir=/app/uploads/exams

# =========================
# MAIL
# =========================
brevo.api.key=${BREVO_API_KEY}
app.mail.from=${APP_MAIL_FROM:examguard.system@gmail.com}

# =========================
# REGISTRAR API
# =========================
registrar.api.base-url=${REGISTRAR_API_BASE_URL:https://69eda66eaf4ff533142bd1b1.mockapi.io/registrar/}
registrar.sync-on-startup=false

# =========================
# APP BASE URL
# =========================
app.base-url=${APP_BASE_URL}

# =========================
# JWT
# =========================
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

# =========================
# FLYWAY
# =========================
spring.flyway.enabled=false