package com.example.backend.service.faculty;

import com.example.backend.dto.faculty.students.*;
import com.example.backend.report.faculty.StudentRosterExcelExportService;
import com.example.backend.report.faculty.StudentRosterExportService;
import com.example.backend.repository.cache.FacultyLoadCacheRepository;
import com.example.backend.repository.cache.StudentProfileCacheRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Service
@RequiredArgsConstructor
public class FacultyStudentsService {

    private final FacultyLoadCacheRepository facultyLoadCacheRepository;
    private final StudentProfileCacheRepository studentProfileCacheRepository;
    private final StudentRosterExportService studentRosterExportService;
    private final StudentRosterExcelExportService studentRosterExcelExportService;

    public List<FacultyAcademicPeriodDTO> getAcademicPeriods(
            String employeeId
    ) {
        return facultyLoadCacheRepository.findAcademicPeriodsByFaculty(employeeId);
    }

    public List<FacultyStudentDTO> getStudentsByPeriod(
            String employeeId,
            String academicYear,
            String term
    ) {
        return studentProfileCacheRepository.findStudentsByFacultyPeriod(
                employeeId,
                academicYear,
                term
        );
    }

    public byte[] exportStudentsRoster(
            String facultyId,
            String academicYear,
            String term,
            String courseCode,
            String programCode,
            String yearLevel,
            String sectionName,
            String type
    ) {
        List<FacultyStudentDTO> students =
                getStudentsByFilters(
                        facultyId,
                        academicYear,
                        term,
                        courseCode,
                        programCode,
                        yearLevel,
                        sectionName
                );

        List<FacultyStudentDTO> distinctStudents =
                removeDuplicateStudents(students);

        String generatedBy =
                "Generated By: "
                        + facultyId
                        + " | "
                        + ZonedDateTime.now(ZoneId.of("Asia/Manila"))
                        .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

        if ("excel".equalsIgnoreCase(type)) {
            return studentRosterExcelExportService.generate(distinctStudents);
        }

        return studentRosterExportService.generatePdf(
                distinctStudents,
                null,
                generatedBy
        );
    }

    private List<FacultyStudentDTO> removeDuplicateStudents(
            List<FacultyStudentDTO> students
    ) {
        Map<String, FacultyStudentDTO> unique = new LinkedHashMap<>();

        for (FacultyStudentDTO student : students) {
            unique.putIfAbsent(student.studentId(), student);
        }

        return List.copyOf(unique.values());
    }

    public List<FacultyStudentDTO> getStudentsByFilters(
            String employeeId,
            String academicYear,
            String term,
            String courseCode,
            String programCode,
            String yearLevel,
            String sectionName
    ) {
        boolean hasCourse =
                courseCode != null && !courseCode.isBlank();

        boolean hasSection =
                programCode != null && !programCode.isBlank()
                        && yearLevel != null
                        && sectionName != null && !sectionName.isBlank();

        if (!hasCourse && !hasSection) {
            return studentProfileCacheRepository.findStudentsByFacultyPeriod(
                    employeeId,
                    academicYear,
                    term
            );
        }

        if (hasCourse && !hasSection) {
            return studentProfileCacheRepository.findStudentsByFacultyCourse(
                    employeeId,
                    academicYear,
                    term,
                    courseCode
            );
        }

        if (!hasCourse) {
            return studentProfileCacheRepository.findStudentsByFacultySectionGroup(
                    employeeId,
                    academicYear,
                    term,
                    programCode,
                    yearLevel,
                    sectionName
            );
        }

        return studentProfileCacheRepository.findStudentsByFacultyCourseAndSectionGroup(
                employeeId,
                academicYear,
                term,
                courseCode,
                programCode,
                yearLevel,
                sectionName
        );
    }
}