package com.example.backend.report.admin;

import com.example.backend.dto.admin.users.AdminUsersExportRequest;
import com.example.backend.dto.admin.users.AdminUserRowDto;
import com.example.backend.entity.core.UserAccess;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Component;

import java.io.ByteArrayOutputStream;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Component
public class AdminUsersExcelExporter {

    private static final ZoneId MANILA = ZoneId.of("Asia/Manila");

    public byte[] export(
            List<AdminUserRowDto> rows,
            AdminUsersExportRequest request,
            UserAccess user
    ) {
        try (
                Workbook workbook = new XSSFWorkbook();
                ByteArrayOutputStream out = new ByteArrayOutputStream()
        ) {
            Sheet sheet = workbook.createSheet("Users");

            CellStyle titleStyle = titleStyle(workbook);
            CellStyle metaStyle = metaStyle(workbook);
            CellStyle headerStyle = headerStyle(workbook);
            CellStyle bodyStyle = bodyStyle(workbook);

            int r = 0;

            Row title = sheet.createRow(r++);
            title.createCell(0).setCellValue("ExamGuard | User Report");
            title.getCell(0).setCellStyle(titleStyle);

            r++;

            Row generated = sheet.createRow(r++);
            generated.createCell(0).setCellValue(buildGeneratedByText(user));
            generated.getCell(0).setCellStyle(metaStyle);

            Row filters = sheet.createRow(r++);
            filters.createCell(0).setCellValue(buildFilterSummary(request));
            filters.getCell(0).setCellStyle(metaStyle);

            r++;

            boolean studentReport = isStudentReport(request);

            String[] headers = studentReport
                    ? new String[]{
                    "School ID", "Username", "Full Name", "Email",
                    "College", "Program", "Year", "Registrar Status", "System Access"
            }
                    : new String[]{
                    "School ID", "Username", "Full Name", "Email",
                    "Registrar Status", "System Access"
            };

            Row header = sheet.createRow(r++);

            for (int i = 0; i < headers.length; i++) {
                Cell cell = header.createCell(i);
                cell.setCellValue(headers[i]);
                cell.setCellStyle(headerStyle);
            }

            for (AdminUserRowDto row : rows) {
                Row data = sheet.createRow(r++);

                Object[] values = studentReport
                        ? new Object[]{
                        row.getSchoolId(),
                        row.getUsername(),
                        row.getFullName(),
                        row.getEmail(),
                        row.getCollegeCode(),
                        row.getProgramCode(),
                        row.getYearLevel(),
                        row.getRegistrarStatus(),
                        row.getSystemAccess()
                }
                        : new Object[]{
                        row.getSchoolId(),
                        row.getUsername(),
                        row.getFullName(),
                        row.getEmail(),
                        row.getRegistrarStatus(),
                        row.getSystemAccess()
                };

                for (int i = 0; i < values.length; i++) {
                    Cell cell = data.createCell(i);
                    cell.setCellValue(value(values[i]));
                    cell.setCellStyle(bodyStyle);
                }
            }

            for (int i = 0; i < headers.length; i++) {
                sheet.autoSizeColumn(i);
                if (sheet.getColumnWidth(i) > 9000) {
                    sheet.setColumnWidth(i, 9000);
                }
            }

            sheet.createFreezePane(0, 6);

            workbook.write(out);
            return out.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException("Failed to export admin users Excel.", e);
        }
    }

    private boolean isStudentReport(AdminUsersExportRequest request) {
        return request != null
                && request.getRole() != null
                && request.getRole().equalsIgnoreCase("STUDENT");
    }

    private String buildGeneratedByText(UserAccess user) {
        String actor = user == null
                ? "Unknown"
                : safe(user.getSchoolId()) + " | " + safe(user.getUsername());

        String generatedAt = java.time.ZonedDateTime.now(MANILA)
                .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

        return "Generated By: " + actor + " | " + generatedAt;
    }

    private String buildFilterSummary(AdminUsersExportRequest request) {

        return "Role: " + safe(request.getRole()) +
                " | Status: " + safe(request.getStatus()) +
                " | Keyword: " + safe(request.getKeyword()) +
                " | Reactivation: " + safe(request.getReactivation());
    }

    private CellStyle titleStyle(Workbook workbook) {
        Font font = workbook.createFont();
        font.setBold(true);
        font.setFontHeightInPoints((short) 14);
        font.setColor(IndexedColors.DARK_RED.getIndex());

        CellStyle style = workbook.createCellStyle();
        style.setFont(font);
        return style;
    }

    private CellStyle metaStyle(Workbook workbook) {
        Font font = workbook.createFont();
        font.setFontHeightInPoints((short) 9);
        font.setColor(IndexedColors.GREY_50_PERCENT.getIndex());

        CellStyle style = workbook.createCellStyle();
        style.setFont(font);
        style.setWrapText(true);
        return style;
    }

    private CellStyle headerStyle(Workbook workbook) {
        Font font = workbook.createFont();
        font.setBold(true);
        font.setColor(IndexedColors.WHITE.getIndex());

        CellStyle style = workbook.createCellStyle();
        style.setFont(font);
        style.setFillForegroundColor(IndexedColors.DARK_RED.getIndex());
        style.setFillPattern(FillPatternType.SOLID_FOREGROUND);
        style.setAlignment(HorizontalAlignment.CENTER);
        style.setVerticalAlignment(VerticalAlignment.CENTER);
        style.setWrapText(true);
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderTop(BorderStyle.THIN);
        style.setBorderLeft(BorderStyle.THIN);
        style.setBorderRight(BorderStyle.THIN);
        return style;
    }

    private CellStyle bodyStyle(Workbook workbook) {
        Font font = workbook.createFont();
        font.setFontHeightInPoints((short) 9);

        CellStyle style = workbook.createCellStyle();
        style.setFont(font);
        style.setWrapText(true);
        style.setVerticalAlignment(VerticalAlignment.TOP);
        style.setBorderBottom(BorderStyle.THIN);
        style.setBorderTop(BorderStyle.THIN);
        style.setBorderLeft(BorderStyle.THIN);
        style.setBorderRight(BorderStyle.THIN);
        return style;
    }

    private String value(Object value) {
        if (value == null) return "-";
        String text = String.valueOf(value);
        return text.isBlank() ? "-" : text;
    }

    private String safe(String value) {
        return value == null || value.isBlank() ? "-" : value;
    }
}